package com.twentyat.model;

// Generated 8 Mar, 2011 1:36:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FriendsMapping generated by hbm2java
 */
@Entity
@Table(name = "friends_mapping", catalog = "twentyat")
public class FriendsMapping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer friendsMappingId;
	private TwentyatUser twentyatUser;
	private TwentyatGroup twentyatGroup;

	public FriendsMapping() {
	}

	public FriendsMapping(TwentyatUser twentyatUser, TwentyatGroup twentyatGroup) {
		this.twentyatUser = twentyatUser;
		this.twentyatGroup = twentyatGroup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "friends_mapping_id", unique = true, nullable = false)
	public Integer getFriendsMappingId() {
		return this.friendsMappingId;
	}

	public void setFriendsMappingId(Integer friendsMappingId) {
		this.friendsMappingId = friendsMappingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "friends_id", nullable = false)
	public TwentyatUser getTwentyatUser() {
		return this.twentyatUser;
	}

	public void setTwentyatUser(TwentyatUser twentyatUser) {
		this.twentyatUser = twentyatUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "twentyat_group_id", nullable = false)
	public TwentyatGroup getTwentyatGroup() {
		return this.twentyatGroup;
	}

	public void setTwentyatGroup(TwentyatGroup twentyatGroup) {
		this.twentyatGroup = twentyatGroup;
	}

}
