package com.twentyat.model;

// Generated 8 Mar, 2011 1:36:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "twentyat")
public class Message implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int messageId;
	private TwentyatUser twentyatUser;
	private Date datetime;
	private String messageText;
	private Integer parentId;
	private Set<Recipient> recipients = new HashSet<Recipient>(0);

	public Message() {
	}

	public Message(int messageId, TwentyatUser twentyatUser) {
		this.messageId = messageId;
		this.twentyatUser = twentyatUser;
	}

	public Message(int messageId, TwentyatUser twentyatUser, Date datetime,
			String messageText, Integer parentId, Set<Recipient> recipients) {
		this.messageId = messageId;
		this.twentyatUser = twentyatUser;
		this.datetime = datetime;
		this.messageText = messageText;
		this.parentId = parentId;
		this.recipients = recipients;
	}

	@Id
	@Column(name = "message_id", unique = true, nullable = false)
	public int getMessageId() {
		return this.messageId;
	}

	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sender_id", nullable = false)
	public TwentyatUser getTwentyatUser() {
		return this.twentyatUser;
	}

	public void setTwentyatUser(TwentyatUser twentyatUser) {
		this.twentyatUser = twentyatUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	@Column(name = "message_text", length = 45)
	public String getMessageText() {
		return this.messageText;
	}

	public void setMessageText(String messageText) {
		this.messageText = messageText;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "message", cascade=CascadeType.ALL)
	public Set<Recipient> getRecipients() {
		return this.recipients;
	}

	public void setRecipients(Set<Recipient> recipients) {
		this.recipients = recipients;
	}

}
