package com.twentyat.model;

// Generated 8 Mar, 2011 1:36:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Recipient generated by hbm2java
 */
@Entity
@Table(name = "recipient", catalog = "twentyat")
public class Recipient implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int recipientId;
	private Message message;

	public Recipient() {
	}

	public Recipient(int recipientId, Message message) {
		this.recipientId = recipientId;
		this.message = message;
	}

	@Id
	@Column(name = "recipient_id", unique = true, nullable = false)
	public int getRecipientId() {
		return this.recipientId;
	}

	public void setRecipientId(int recipientId) {
		this.recipientId = recipientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "message_id", nullable = false)
	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

}
