package com.twentyat.model;

// Generated 8 Mar, 2011 1:36:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TwentyatGroup generated by hbm2java
 */
@Entity
@Table(name = "twentyat_group", catalog = "twentyat")
public class TwentyatGroup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer twentyatGroupId;
	private TwentyatUser twentyatUser;
	private String groupName;
	private Set<FriendsMapping> friendsMappings = new HashSet<FriendsMapping>(0);

	public TwentyatGroup() {
	}

	public TwentyatGroup(TwentyatUser twentyatUser, String groupName,
			Set<FriendsMapping> friendsMappings) {
		this.twentyatUser = twentyatUser;
		this.groupName = groupName;
		this.friendsMappings = friendsMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "twentyat_group_id", unique = true, nullable = false)
	public Integer getTwentyatGroupId() {
		return this.twentyatGroupId;
	}

	public void setTwentyatGroupId(Integer twentyatGroupId) {
		this.twentyatGroupId = twentyatGroupId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "twentyat_user_id")
	public TwentyatUser getTwentyatUser() {
		return this.twentyatUser;
	}

	public void setTwentyatUser(TwentyatUser twentyatUser) {
		this.twentyatUser = twentyatUser;
	}

	@Column(name = "group_name", length = 45)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "twentyatGroup", cascade=CascadeType.ALL)
	public Set<FriendsMapping> getFriendsMappings() {
		return this.friendsMappings;
	}

	public void setFriendsMappings(Set<FriendsMapping> friendsMappings) {
		this.friendsMappings = friendsMappings;
	}

}
