package com.twentyat.model;

// Generated 8 Mar, 2011 1:36:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TwentyatUser generated by hbm2java
 */
@Entity
@Table(name = "twentyat_user", catalog = "twentyat")
public class TwentyatUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String twentyatUserId;
	private String firstName;
	private String lastName;
	private String email;
	private String mobilePhone;
	private String photo;
	private String friendlyName;
	private String middleName;
	private Long facebookId;
	private Boolean isActive;
	private String streetAddress;
	private String locality;
	private String region;
	private Integer postalCode;
	private String country;
	private Set<TwentyatGroup> twentyatGroups = new HashSet<TwentyatGroup>(0);
	private Set<FriendsMapping> friendsMappings = new HashSet<FriendsMapping>(0);
	private Set<ContactPerson> contactPersons = new HashSet<ContactPerson>(0);
	private Set<Message> messages = new HashSet<Message>(0);

	public TwentyatUser() {
	}

	public TwentyatUser(String twentyatUserId) {
		this.twentyatUserId = twentyatUserId;
	}

	public TwentyatUser(String twentyatUserId, String firstName,
			String lastName, String email, String mobilePhone, String photo,
			String friendlyName, String middleName, Long facebookId,
			Boolean isActive, String streetAddress, String locality,
			String region, Integer postalCode, String country,
			Set<TwentyatGroup> twentyatGroups, Set<FriendsMapping> friendsMappings, 
			Set<ContactPerson> contactPersons,
			Set<Message> messages) {
		this.twentyatUserId = twentyatUserId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.mobilePhone = mobilePhone;
		this.photo = photo;
		this.friendlyName = friendlyName;
		this.middleName = middleName;
		this.facebookId = facebookId;
		this.isActive = isActive;
		this.streetAddress = streetAddress;
		this.locality = locality;
		this.region = region;
		this.postalCode = postalCode;
		this.country = country;
		this.twentyatGroups = twentyatGroups;
		this.friendsMappings = friendsMappings;
		this.contactPersons = contactPersons;
		this.messages = messages;
	}

	@Id
	@Column(name = "twentyat_user_id", unique = true, nullable = false, length = 45)
	public String getTwentyatUserId() {
		return this.twentyatUserId;
	}

	public void setTwentyatUserId(String twentyatUserId) {
		this.twentyatUserId = twentyatUserId;
	}

	@Column(name = "first_name", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "mobile_phone", length = 45)
	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	@Column(name = "photo")
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "friendly_name")
	public String getFriendlyName() {
		return this.friendlyName;
	}

	public void setFriendlyName(String friendlyName) {
		this.friendlyName = friendlyName;
	}

	@Column(name = "middle_name", length = 45)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "facebook_id")
	public Long getFacebookId() {
		return this.facebookId;
	}

	public void setFacebookId(Long facebookId) {
		this.facebookId = facebookId;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "street_address", length = 100)
	public String getStreetAddress() {
		return this.streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	@Column(name = "locality", length = 50)
	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	@Column(name = "region", length = 50)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "postal_code")
	public Integer getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(Integer postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "country", length = 30)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "twentyatUser", cascade=CascadeType.ALL)
	public Set<TwentyatGroup> getTwentyatGroups() {
		return this.twentyatGroups;
	}

	public void setTwentyatGroups(Set<TwentyatGroup> twentyatGroups) {
		this.twentyatGroups = twentyatGroups;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "twentyatUser", cascade=CascadeType.ALL)
	public Set<FriendsMapping> getFriendsMappings() {
		return this.friendsMappings;
	}

	public void setFriendsMappings(Set<FriendsMapping> friendsMappings) {
		this.friendsMappings = friendsMappings;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "twentyatUser", cascade=CascadeType.ALL)
	public Set<ContactPerson> getContactPersons() {
		return this.contactPersons;
	}

	public void setContactPersons(Set<ContactPerson> contactPersons) {
		this.contactPersons = contactPersons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "twentyatUser", cascade=CascadeType.ALL)
	public Set<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

}
